<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ja" sourcelanguage="en">
  <context>
    <name>@default</name>
    <message>
      <source>NETGEN_2D_HYPOTHESIS</source>
      <translation>Netgen 2D</translation>
    </message>
    <message>
      <source>NETGEN_2D_TITLE</source>
      <translation>設定項目</translation>
    </message>
    <message>
      <source>NETGEN_3D_HYPOTHESIS</source>
      <translation>Netgen 3D</translation>
    </message>
    <message>
      <source>NETGEN_3D_TITLE</source>
      <translation>設定項目</translation>
    </message>
    <message>
      <source>NETGEN_SimpleParameters_3D_HYPOTHESIS</source>
      <translation>Netgen 3D 簡易パラメーター</translation>
    </message>
    <message>
      <source>NETGEN_SimpleParameters_3D_TITLE</source>
      <translation>設定項目</translation>
    </message>
    <message>
      <source>NETGEN_SimpleParameters_2D_HYPOTHESIS</source>
      <translation>Netgen 2D 簡易パラメーター</translation>
    </message>
    <message>
      <source>NETGEN_SimpleParameters_2D_TITLE</source>
      <translation>設定項目</translation>
    </message>
    <message>
      <source>NETGEN_ALLOW_QUADRANGLES</source>
      <translation>四角形を許可</translation>
    </message>
    <message>
      <source>NETGEN_COARSE</source>
      <translation>粗い</translation>
    </message>
    <message>
      <source>NETGEN_CUSTOM</source>
      <translation>カスタム</translation>
    </message>
    <message>
      <source>NETGEN_FINE</source>
      <translation>細かい</translation>
    </message>
    <message>
      <source>NETGEN_FINENESS</source>
      <translation>細かさ</translation>
    </message>
    <message>
      <source>NETGEN_FUSE_EDGES</source>
      <translation>エッジ及び頂点上の一致節点を結合</translation>
    </message>
    <message>
      <source>NETGEN_GROWTH_RATE</source>
      <translation>増加率</translation>
    </message>
    <message>
      <source>NETGEN_MAX_SIZE</source>
      <translation>最大サイズ</translation>
    </message>
    <message>
      <source>NETGEN_MIN_SIZE</source>
      <translation>最小サイズ</translation>
    </message>
    <message>
      <source>NETGEN_MODERATE</source>
      <translation>普通</translation>
    </message>
    <message>
      <source>NETGEN_OPTIMIZE</source>
      <translation>最適化</translation>
    </message>
    <message>
      <source>NETGEN_SECOND_ORDER</source>
      <translation>2次要素</translation>
    </message>
    <message>
      <source>NETGEN_SEG_PER_EDGE</source>
      <translation>エッジ上の分割数</translation>
    </message>
    <message>
      <source>NETGEN_SEG_PER_RADIUS</source>
      <translation>半径毎の分割数</translation>
    </message>
    <message>
      <source>NETGEN_SURFACE_CURVATURE</source>
      <translation>面の極率による限界サイズ</translation>
    </message>
    <message>
      <source>NETGEN_VERYCOARSE</source>
      <translation>非常に粗く</translation>
    </message>
    <message>
      <source>NETGEN_VERYFINE</source>
      <translation>非常に細かく</translation>
    </message>
    <message>
      <source>NG_1D</source>
      <translation>1D</translation>
    </message>
    <message>
      <source>NG_2D</source>
      <translation>2D</translation>
    </message>
    <message>
      <source>NG_3D</source>
      <translation>3D</translation>
    </message>
    <message>
      <source>NG_LENGTH_FROM_EDGES</source>
      <translation>エッジの長さ</translation>
    </message>
    <message>
      <source>NG_LENGTH_FROM_FACES</source>
      <translation>フェースの長さ</translation>
    </message>
    <message>
      <source>NETGEN_LOCAL_SIZE</source>
      <translation>ローカルのサイズ</translation>
    </message>
    <message>
      <source>NETGEN_LSZ_VERTEX</source>
      <translation>頂点</translation>
    </message>
    <message>
      <source>NETGEN_LSZ_EDGE</source>
      <translation>エッジ上</translation>
    </message>
    <message>
      <source>NETGEN_LSZ_FACE</source>
      <translation>サブフェース上</translation>
    </message>
    <message>
      <source>NETGEN_LSZ_SOLID</source>
      <translation>ソリッド上</translation>
    </message>
    <message>
      <source>NETGEN_LSZ_REMOVE</source>
      <translation>削除</translation>
    </message>
    <message>
      <source>LSZ_ENTRY_COLUMN</source>
      <translation>エントリ</translation>
    </message>
    <message>
      <source>LSZ_NAME_COLUMN</source>
      <translation>名前</translation>
    </message>
    <message>
      <source>LSZ_LOCALSIZE_COLUMN</source>
      <translation>値</translation>
    </message>
    <message>
      <source>NETGEN_LSZ_FILE</source>
      <translation>メッシュサイズファイル</translation>
    </message>
  </context>
</TS>
