#!/bin/sh

src_dir=${1}
install_dir=${2}

if ! test -d ${src_dir}/libsrc ; then
    echo "No dir ${src_dir}/libsrc ... Bye"
    exit 1
fi
if ! test -d ${install_dir} ; then
    echo "No dir ${install_dir} ... Bye"
    exit 1
fi

dest_dir=${install_dir}/include
mkdir -p ${dest_dir} > /dev/null 2>&1

for directory in csg general geom2d gprim interface linalg meshing stlgeom visualization
do
    cp -af ${src_dir}/libsrc/${directory}/*.hpp ${dest_dir}
done
cp -af ${src_dir}/libsrc/include/mystdlib.h ${dest_dir}
cp -af ${src_dir}/libsrc/include/mydefs.hpp ${dest_dir}
cp -af ${src_dir}/libsrc/occ/occgeom.hpp ${dest_dir}
cp -af ${src_dir}/libsrc/occ/occmeshsurf.hpp ${dest_dir}
cp -af ${src_dir}/libsrc/general/gzstream.h ${dest_dir}
test -f ${src_dir}/config.h && cp -af ${src_dir}/config.h ${dest_dir}
